# <font color='blue'> **Data 3650 - Winter 2023**
## <font color='darkcyan'> **Assignment 1** : 22 points
   - Due date: Please check on Moodle.
   - Please create additional cells (if necessary) to write your code under the questions.
   - You must submit a single .ipynb file using the link on Moodle. Files in other formats will not be acceptable.
   - Please ensure that you are not changing any part of the questions. 
   - Sample answers are provided for certain problems to notify you about the expected output.
   - Please execute the following cell to write your name and student ID

In [3]:
# Please run this cell to provide your name and ID
name = input('Enter your name: ')
_id = input("Enter your student ID: ")
print('Name: {} - ID: {}'.format(name, _id))

Enter your name:  Austin
Enter your student ID:  200380350


Name: Austin - ID: 200380350


### <font color='red'>Que 1:</font> Consider the following list. Using the concept of indexing, print the list element 'NAIT'.  <font color='green'>(2 point)

In [4]:
aList = [-10,2,[5,8],[3,7,['A','B',['C','D',['NAIT']],89,23],10],'W','Z']

In [5]:
# Write your code from here.
aList[3][2][2][2]

['NAIT']

### <font color='red'>Que 2:</font> Consider the following dictionary. Print the value 'Edmonton'. <font color='green'>(2 point)

In [6]:
cities = {'ON':['Toronto','Ottawa',{'BC':['Vancouver','Surrey',{'AB':['Calgary','Edmonton','Lethbridge']}]}]}

In [7]:
# Write your code from here.
cities['ON'][2]['BC'][2]['AB'][1]

'Edmonton'

### <font color='red'> Que 3: </font> Write a function that can accept n numbers of email addresses, and return all the user names. For example, the function should return asifn and xyz if the email addresses are asifn@nait.ca and xyz@gmail.com respectively. <font color='green'>(2 point)

In [2]:
# Write your code from here.
def emailUsers():
        emails = []
        num = int(input('Please enter number of emails: '))
        for i in range(num):
            email = input('Please enter emails (ex. Bob@gmail.com): ')
            user = email.split('@')[0]
            emails.append(user)
    
        for item in emails:
            print(item)
emailUsers()

Please enter number of email addresses:  2
Please enter email address (ex. Bob@gmail.com):  austin@gmail.com
Please enter email address (ex. Bob@gmail.com):  bob@gmail.com


austin
bob


### <font color='red'> Que 4: </font> Write a function that accepts two lists (list data structure) of fruit names as parameters, and returns the names of the fruits that appear in both lists. Write appropriate function call to show that your function is generating the correct output. Note: The names of the fruits can appear in the lists in either upper case or lower case, and your code must handle this case. <font color='green'>(4 point)

In [9]:
# Write your code from here.
def fruitNames(list1, list2):
    return list1, list2

fruit1 = ['Pineapple', 'Mango', 'Banana']
fruit2 = ['strawberry', 'grapes', 'cherry']

fruitNames(fruit1,fruit2)

(['Pineapple', 'Mango', 'Banana'], ['strawberry', 'grapes', 'cherry'])

### <font color='red'> Que 5: </font> (a) Create the following matrix. (b) Convert all the numbers to 0 except the diagonal elements of the matrix you created in part (a). See the expected output. <font color='green'>(3 point)

In [115]:
# Write your code from here.
# Part (a)
import numpy as np

arr = np.arange(0.01, 1.01, 0.01).reshape(10,10)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [129]:
# Part (b)
arr[:1, 1:10] = 0
arr[1][0] = 0
arr[:2, 2:10] = 0
arr[2][0:2] = 0
arr[:3, 3:10] = 0
arr[3][0:3] = 0
arr[:4, 4:10] = 0
arr[4][0:4] = 0
arr[:5, 5:10] = 0
arr[5][0:5] = 0
arr[:6, 6:10] = 0
arr[6][0:6] = 0
arr[:7, 7:10] = 0
arr[7][0:7] = 0
arr[:8, 8:10] = 0
arr[8][0:8] = 0
arr[:9, 9:10] = 0
arr[9][0:9] = 0
arr[:10, 10:10] = 0
print(arr)

[[0.01 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.12 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.23 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.34 0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.45 0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.56 0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.67 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.78 0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.89 0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   1.  ]]


### <font color='red'> Que 6: </font> (a) Create the following matrix. (b) Write the code to get the following elements from the matrix you created in part (a). <font color='green'>(3 point)


In [68]:
# Write your code from here.
# Part (a)
arr2 = np.arange(1, 101, 1).reshape(10,10)
print(arr2)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [214]:
# Part (b)
print(arr2[[4, 5, 6], 4:9])

[[45 46 47 48 49]
 [55 56 57 58 59]
 [65 66 67 68 69]]


### <font color='red'> Que 7: </font> Create the following matrix. <font color='green'>(3 point)

In [143]:
# Write your code from here.
arr_zeros = np.zeros((7,7))
arr_zeros[:,0] = 1
arr_zeros[0] = 1
arr_zeros[:,-1] = 1
arr_zeros[-1] = 1
arr_zeros[3][3] = 7
print(arr_zeros)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 7. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


### <font color='red'> Que 8: </font> Write a Python code that takes a line of text as user input. Define a function that will take the user input as a parameter and returns a list of digits that appear in the user input. You <font color = 'brown'><u>must</u></font> use the concept of list comprehension to create the list. See the sample outputs. <font color='green'>(3 point)

In [195]:
# Write your code from here.
def numSplit():
    userInput = input('Enter your text: ')
    numbers = [num for num in userInput if num.isdigit()]
    print(numbers)


In [196]:
# sample run: 1
numSplit()

Enter your text:  DATA3650 Advanc3d 7echniqu3


['3', '6', '5', '0', '3', '7', '3']


In [197]:
# sample run: 2
numSplit()

Enter your text:  Data Analytics


[]


In [198]:
# sample run: 3
numSplit()

Enter your text:  T0 8E 0R N07 70 8E


['0', '8', '0', '0', '7', '7', '0', '8']
